security:
    encoders:
        # App\Entity\UserEntity:
        #     algorithm: auto
        App\Entity\UserRegistration:
            algorithm: auto
            #  algorithm: bcrypt


    providers:

        app_user_provider:
            entity:
                class: App\Entity\UserRegistration
                property: username
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        # if you wanted to force EVERY URL to be protected
        # - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }